name: "Automated Puppet"
description: "Scheduled screenshot capture of Home Assistant dashboards"
version: "2.0.0"
slug: "automated-puppet"
homeassistant_api: true
init: false
arch:
  - aarch64
  - amd64
options:
  access_token: ""
  home_assistant_url: "http://homeassistant:8123"
schema:
  access_token: str
  home_assistant_url: str
